config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  namespace :home do
    get 'personal'
    get 'life'
    get 'about'
    get 'contact'
    post 'feedback'
    post 'sidekiq_job'
  end

  resources :photos



  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
   mount_uploader :file, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def personal

  end

  def life

  end

  def about

  end

  def contact

  end

  def feedback

  end

  def sidekiq_job
    count = params[:sidekiq_job][:count].present? ? params[:sidekiq_job][:count] : 1
    count.to_i.times do
      HardWorkerJob.set(wait: params[:sidekiq_job][:delay].present? ? params[:sidekiq_job][:delay].to_i.seconds : 0.seconds).perform_later({name: 'bobo'})
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index

  end

  def show

  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new
    @photo.file = params[:photo][:file]
    if @photo.save
      render 'index'
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/contact.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-3 contant_info">
CONTACT INFORMATION
<div>
  AENEAN NONUMMY HENDRERIT MAURIS. PHASELLUS PORTA. FUSCE SUSCIPIT VARIUS MI. CUM SOCIIS NATOQUE PENATIBUS ET MAGNIS DIS PARTURIENT MONTES, NASCETUR RIDICULUS MUS. NULLA DUI. FUSCE FEUGIAT MALESUADA ODIO.

8901 MARMORA ROAD, GLASGOW, D04 89GR.
FREEPHONE: +1 800 559 6580
TELEPHONE: +1 800 603 6035
FAX: +1 800 889 9898
E-MAIL: MAIL@DEMOLINK.ORG
</div>
  </div>
  <div class="col-md-3 feedback">
    <%= form_for 'test', url: home_feedback_path, method: :post,  html: {class: 'form-vertical'} do |f| %>
    <%= f.text_field :name, placeholder: 'NAME', class: 'form-control' %>
    <%= f.text_field :email, placeholder: 'EMAIL', class: 'form-control' %>
    <%= f.text_area :message, placeholder: 'MESSAGE', class: 'form-control'  %>
    <%= f.submit :Send, class: 'btn btn-primary btn btn-block' %>
    <% end %>
  </div>
</div>



<%= form_for :sidekiq_job, url: home_sidekiq_job_path, html: {remote: true, class: 'form-horizontal', style: 'margin-top: 100px;'} do |f| %>
  <div class="form-group">
    <%= f.label :count, '任务条数', class: 'col-sm-2 control-label' %>
    <div class="col-md-2">
      <%= f.text_field :count, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :delay, '延迟执行(Sec)', class: 'col-sm-2 control-label' %>
    <div class="col-md-2">
      <%= f.text_field :delay, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-2 col-md-offset-2">
      <%= f.submit '开始执行', class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-2 col-md-offset-2">
      <%= link_to 'sidekiq后台监控页面', sidekiq_web_path, class: 'btn btn-primary', target: '_blank' %>
    </div>
  </div>
<% end %>

<style>
.contant_info,.feedback{
  text-align: center;
}
.feedback input,textarea,button{
  margin-bottom: 15px;
}
</style>

app/views/home/index.html.erb
<%= link_to 'upload photos', new_photo_path %>

<button class="filter btn btn-danger" data-filter="all">all</button>
<button class="filter btn btn-default" data-filter=".category-1">Category 1</button>
<button class="filter btn btn-success" data-filter=".category-2">Category 2</button>

<div id="list">
  <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/1.jpg'), image_url('fullscreen/1.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/2.jpg'), image_url('fullscreen/2.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/3.jpg'), image_url('fullscreen/3.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

  <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/1.jpg'), image_url('fullscreen/1.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/2.jpg'), image_url('fullscreen/2.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/3.jpg'), image_url('fullscreen/3.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/3.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/2.jpg'), image_url('fullscreen/2.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
  </div>

   <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/1.jpg'), image_url('fullscreen/1.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
    <!-- <div class="info"></div> -->
  </div>

   <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
    <!-- <div class="info">test</div> -->
  </div>

   <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
    <!-- <div class="info">Thumbs</div> -->
  </div>
  <div class="imgWrap mix category-2">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
    <!-- <div class="info">Thumbs</div> -->
  </div>
  <div class="imgWrap mix category-1">
    <div class="bg1"></div>
    <div class="bg2"></div>
    <div class="imgDiv">
      <div><%= link_to image_tag('thumbnails/4.jpg'), image_url('fullscreen/4.jpg'), class: 'fancybox', rel: "fancybox-thumb" , title: "You can add caption to pictures." %></div>
    </div>
    <!-- <div class="info">Thumbs</div> -->
  </div>
</div>



<style>

  #list .mix{
    text-align: center;
    display: none;
  }


</style>


<script>
  $(function(){
    $('#list').mixItUp();


    $('.fancybox').fancybox();

    $(".filter").on("click", function () {
       // get 'data-filter' value of the button clicked
       var $fancyFilter = $(this).attr('data-filter');
       // test the value of $fancyFilter and change 'rel' attribute according to it
       switch($fancyFilter)
       {
         case '.category-1':$(".category-1 .fancybox").attr("rel","category-1");
         break;
         case '.category-2':$(".category-2 .fancybox").attr("rel","category-2");
         break;
         default:$(".mix .fancybox").attr("rel","gallery");
       }
    });

  });

</script>

app/views/home/life.html.erb
<link href='http://fonts.googleapis.com/css?family=Droid+Serif|Open+Sans:400,700' rel='stylesheet' type='text/css'>

<section id="cd-timeline" class="cd-container">
    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-picture">
        <%= image_tag('cd-icon-picture.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 1</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Jan 14</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-movie">
        <%= image_tag('cd-icon-movie.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 2</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde?</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Jan 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-picture">
        <%= image_tag('cd-icon-picture.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 3</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, obcaecati, quisquam id molestias eaque asperiores voluptatibus cupiditate error assumenda delectus odit similique earum voluptatem doloremque dolorem ipsam quae rerum quis. Odit, itaque, deserunt corporis vero ipsum nisi eius odio natus ullam provident pariatur temporibus quia eos repellat consequuntur perferendis enim amet quae quasi repudiandae sed quod veniam dolore possimus rem voluptatum eveniet eligendi quis fugiat aliquam sunt similique aut adipisci.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Jan 24</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 4</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 14</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 5</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 5</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 5</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 5</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-location">
        <%= image_tag('cd-icon-location.svg') %>
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Title of section 5</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
        <a href="#0" class="cd-read-more">Read more</a>
        <span class="cd-date">Feb 18</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->
    <div class="cd-timeline-block">
      <div class="cd-timeline-img cd-movie">
        <%= image_tag('cd-icon-movie.svg') %>

      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h2>Final Section</h2>
        <p>This is the content of the last section</p>
        <span class="cd-date">Feb 26</span>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->
  </section> <!-- cd-timeline -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonPhoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="container">
    <%= render 'shared/navigation' %>
    <div class="main">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

<style>
  .main{
    text-align: center;
    margin-left: 15%;
    margin-right: 15%;
  }
</style>

app/views/photos/index.html.erb
<table>
  <thead>
    <th>url </th>
    <th>current_path </th>
    <th>file_identifier</th>
    <th>photo</th>
    <th>url(:thumb)</th>
    <th>thumb image</th>
  </thead>
  <tbody>
    <% if Photo.count >0 %>
      <% Photo.all.each do |photo| %>
        <tr>
          <td><%= photo.file.url %></td>
          <td><%= photo.file.current_path %></td>
          <td> <%= photo.file_identifier %> </td>
          <td><%= image_tag "#{photo.file.url}" %></td>
          <td><%= photo.file.url(:thumb) %></td>
          <td><%= image_tag "#{photo.file.url(:thumb)}" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/photos/new.html.erb
<%= form_for @photo do |f| %>
  <%= f.file_field :file %>
  <%= f.submit :submit %>
<% end %>

app/views/shared/_navigation.html.erb
  <ul id="nav">
    <li><%= link_to 'Home', root_path, data: { turbolinks: false }%></li>
    <li><%= link_to 'Personal', home_personal_path , data: { turbolinks: false }%></li>
    <li><%= link_to 'Life', home_life_path , data: { turbolinks: false }%></li>
    <li><%= link_to 'Contact', home_contact_path , data: { turbolinks: false }%></li>
  </ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>